apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - name: openai
        type: openai
        credentialsSecretRef:
          name: credentials
        url: https://api.openai.com/v1
        models:
          - name: gpt-5.6-luna
            parameters:
              reasoningConfig:
                effort: high
  ols:
    defaultModel: gpt-5.6-luna
    defaultProvider: openai
    logLevel: DEBUG
